#pragma once

#include <filesystem>

#include "emp/config/ArgManager.hpp"
#include "emp/prefab/ConfigPanel.hpp"
#include "emp/web/UrlParams.hpp"
#include "emp/web/web.hpp"

#include "chemical-ecology/Config.hpp"
#include "chemical-ecology/utils/config_setup.hpp"

// Separated out from config_setup.hpp to avoid compiler warning generated by
// Empirical web code for native compilation.
// No need to include web headers for native builds.

namespace chemical_ecology::utils {

void setup_config_web(chemical_ecology::Config & config)  {
  auto specs = emp::ArgManager::make_builtin_specs(&config);
  emp::ArgManager am(emp::web::GetUrlParams(), specs);
  use_existing_config_file(config, am);
}

} // End of chemical_ecology::utils namespace

