---
title: "Chemical Ecology Proof of Concept"
author: "Emily Dolson"
date: "12/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(ggplot2)
library(dplyr)
all_data <- read_csv("../all_data.csv")
all_data$PROB_CLEAR <- as.factor(all_data$PROB_CLEAR)

ggplot(all_data %>% filter(Time < 2000) ) + stat_summary(aes(x=Time, y=mean_Fitness/81100, fill=PROB_CLEAR, color=PROB_CLEAR, group=PROB_CLEAR), fun.data = "mean_cl_boot", geom="smooth", se=TRUE) + theme_classic() + scale_color_discrete("Probability of disturbance") + scale_fill_discrete("Probability of disturbance") + scale_y_continuous("Mean growth rate\n(normalized)") + theme(legend.position = "bottom", axis.title = element_text(size=18), axis.text = element_text(color="black", size=10)) + annotate("rect", xmin = 0, xmax = 90, ymin = 0, ymax = .47, alpha = .2) + annotate("text", x = 100, y = .65, label = "Pioneer\nsuccessional\nstage") + geom_segment(aes(x = 90, y = .525, xend = 45, yend = .44),arrow = arrow(length = unit(0.2, "cm")))

```
